// Extracts lookup tables from the C reference headers in /root/cQR and
// emits TypeScript modules. Run: npm run gen:tables
// The generated files are checked in; apps using the package never run this.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cRoot = '/root/cQR/include/qrcode/detail';
const outDir = join(root, 'src');

function extract(src, cName) {
  const marker = new RegExp(`${cName}\\s*(\\[[^\\]]*\\]\\s*)+=\\s*\\{`, 'm');
  const m = marker.exec(src);
  if (!m) throw new Error(`table not found: ${cName}`);
  const dims = [...m[0].matchAll(/\[(\d*)\]/g)].map((x) => (x[1] === '' ? 0 : Number(x[1])));
  let i = m.index + m[0].length - 1; // at '{'
  let depth = 0;
  let body = '';
  for (; i < src.length; i++) {
    const ch = src[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) break;
    }
    body += ch;
  }
  const values = body.match(/-?\d+/g).map(Number);
  return { dims, values };
}

function fmtFlat(values, perLine = 16) {
  const lines = [];
  for (let i = 0; i < values.length; i += perLine) {
    lines.push('  ' + values.slice(i, i + perLine).join(', ') + ',');
  }
  return lines.join('\n');
}

function fmtNested(values, dims) {
  // Emits the *contents* of the outermost array (the template provides
  // `= [` ... `];`). dims like [4,41], [41,7], [31,30] or [8,6,6].
  const rowLen = dims[dims.length - 1];
  const rows = values.length / rowLen;
  const rowLines = [];
  for (let r = 0; r < rows; r++) {
    rowLines.push('  [' + values.slice(r * rowLen, (r + 1) * rowLen).join(', ') + '],');
  }
  if (dims.length === 2) return rowLines.join('\n');
  // 3D: group rows into dims[1]-row blocks.
  const perGroup = dims[1];
  const lines = [];
  for (let g = 0; g < rows; g += perGroup) {
    lines.push('  [');
    for (const line of rowLines.slice(g, g + perGroup)) lines.push('  ' + line);
    lines.push('  ],');
  }
  return lines.join('\n');
}

const qrSrc = readFileSync(join(cRoot, 'generated_qr_tables.inc.h'), 'utf8');
const kanjiSrc = readFileSync(join(cRoot, 'generated_kanji_table.inc.h'), 'utf8');

const t = {};
for (const name of [
  'qr_gf_exp',
  'qr_gf_log',
  'qr_rs_generator',
  'qr_ecc_codewords_per_block',
  'qr_num_error_correction_blocks',
  'qr_data_codeword_table',
  'qr_alignment_count',
  'qr_alignment_positions',
  'qr_format_bits',
  'qr_mask_pattern',
  'qr_version_bits',
]) {
  t[name] = extract(qrSrc, name);
}
const k = {};
for (const name of ['qr_kanji_offsets', 'qr_kanji_codepoints', 'qr_kanji_values']) {
  k[name] = extract(kanjiSrc, name);
}
const kanjiCount = Number(/QR_KANJI_UTF8_COUNT\s+(\d+)/.exec(kanjiSrc)[1]);

const core = `// Automatically generated by tools/extract-tables.mjs. Do not edit.
// Source: /root/cQR QR Code lookup tables (see THIRD-PARTY-NOTICES.md).
export const GF_EXP: ReadonlyArray<number> = [
${fmtFlat(t.qr_gf_exp.values)}
];
export const GF_LOG: ReadonlyArray<number> = [
${fmtFlat(t.qr_gf_log.values)}
];
export const RS_GENERATOR: ReadonlyArray<ReadonlyArray<number>> = [
${fmtNested(t.qr_rs_generator.values, t.qr_rs_generator.dims)}
];
export const ECC_PER_BLOCK: ReadonlyArray<ReadonlyArray<number>> = [
${fmtNested(t.qr_ecc_codewords_per_block.values, t.qr_ecc_codewords_per_block.dims)}
];
export const NUM_BLOCKS: ReadonlyArray<ReadonlyArray<number>> = [
${fmtNested(t.qr_num_error_correction_blocks.values, t.qr_num_error_correction_blocks.dims)}
];
export const DATA_CODEWORDS: ReadonlyArray<ReadonlyArray<number>> = [
${fmtNested(t.qr_data_codeword_table.values, t.qr_data_codeword_table.dims)}
];
export const ALIGN_COUNT: ReadonlyArray<number> = [
${fmtFlat(t.qr_alignment_count.values)}
];
export const ALIGN_POS: ReadonlyArray<ReadonlyArray<number>> = [
${fmtNested(t.qr_alignment_positions.values, t.qr_alignment_positions.dims)}
];
export const FORMAT_BITS: ReadonlyArray<ReadonlyArray<number>> = [
${fmtNested(t.qr_format_bits.values, t.qr_format_bits.dims)}
];
export const MASK_PATTERN: ReadonlyArray<ReadonlyArray<ReadonlyArray<number>>> = [
${fmtNested(t.qr_mask_pattern.values, t.qr_mask_pattern.dims)}
];
export const VERSION_BITS: ReadonlyArray<number> = [
${fmtFlat(t.qr_version_bits.values, 8)}
];
`;

const kanjiOffsets = k.qr_kanji_offsets.values;
const kanjiCodepoints = k.qr_kanji_codepoints.values;
const kanjiValues = k.qr_kanji_values.values;
if (kanjiOffsets.length !== 257 || kanjiCodepoints.length !== kanjiCount || kanjiValues.length !== kanjiCount) {
  throw new Error('kanji table shape mismatch');
}
// Pack as little-endian uint16 bytes -> base64 (compact like .rodata in C).
const packed = Buffer.alloc((257 + kanjiCount * 2) * 2);
kanjiOffsets.forEach((v, i) => packed.writeUInt16LE(v, i * 2));
kanjiCodepoints.forEach((v, i) => packed.writeUInt16LE(v, (257 + i) * 2));
kanjiValues.forEach((v, i) => packed.writeUInt16LE(v, (257 + kanjiCount + i) * 2));
const kanjiB64 = packed.toString('base64');
const kanji = `// Automatically generated by tools/extract-tables.mjs. Do not edit.
// Packed little-endian uint16: 257 offsets, ${kanjiCount} codepoints, ${kanjiCount} values.
export const KANJI_COUNT = ${kanjiCount};
export const KANJI_PACKED =
  '${kanjiB64.match(/.{1,120}/g).join("' +\n  '")}';
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'tables.core.generated.ts'), core);
writeFileSync(join(outDir, 'tables.kanji.generated.ts'), kanji);
console.log(`wrote src/tables.core.generated.ts + src/tables.kanji.generated.ts (${kanjiCount} kanji mappings)`);
